apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-forecast
  namespace: ai-forecast
spec:
  ingressClassName: nginx
  rules:
    - host: ai-forecast.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-forecast
                port:
                  number: 8000
