apiVersion: v1
kind: Service
metadata:
  name: ai-forecast
  namespace: ai-forecast
  labels:
    app: ai-forecast
spec:
  type: NodePort
  selector:
    app: ai-forecast
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
    protocol: TCP
    name: http
